import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig([
  // android/ is regenerated by Capacitor (`npx cap add android`) and contains
  // bundled native-bridge.js with eslint-disable directives for plugins this
  // config doesn't load. Treat it as a build artifact, not source.
  globalIgnores(['dist', 'android']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  // Containment guard for useChat.ts. The hook regrew from 770 -> 1,733
  // lines between 2026-03-25 and 2026-04-19 because new features kept
  // landing sibling modules *and* hook-level coordinators. This ceiling
  // blocks silent regression; ratchet it down as phases 2-4 of the
  // re-extraction track land. See docs/decisions/useChat Regression Audit.md.
  //
  // History:
  //   Phase 1 (useQueuedFollowUps): 1,733 -> 1,672, ceiling set to 1,700.
  //   Phase 2 (useRunEventStream):  1,673 -> 1,577, ceiling lowered to 1,620.
  //   Phase 3 (useRunEngine):       1,577 -> 1,465, ceiling lowered to 1,500.
  //   Phase 4 (useVerificationState + usePendingSteer):
  //                                 1,465 -> 1,365, ceiling lowered to 1,400.
  //   Slice 2 (branch-context-preservation):
  //                                 1,396 -> 1,410 after fork-guard hook
  //                                 extraction; ceiling raised to 1,420 to
  //                                 absorb the conversation-fork migration
  //                                 plumbing (skipAutoCreateRef wiring +
  //                                 cross-tab marker early-return + ref
  //                                 propagation to chat-send via
  //                                 SendLoopContext).
  //   Slice 2.1 (UI fork button):
  //                                 1,420 -> 1,448 after the
  //                                 forkBranchFromUI useCallback was added
  //                                 (wraps the sandbox_create_branch tool
  //                                 path and dispatches the BranchSwitchPayload
  //                                 through applyBranchSwitchPayload so the
  //                                 UI button uses the same migration helper
  //                                 as the model path). Ceiling raised to
  //                                 1,450; the callback is internal-ref-
  //                                 heavy and not a clean extraction
  //                                 target. Further reduction should target
  //                                 the auto-switch effect once slice 2.5
  //                                 lands.
  //   Phase 5 (prepareSendContext): 1,450 -> 1,349 after sendMessage's
  //                                 "Prepare context" block (build user
  //                                 message, resolve provider/model lock,
  //                                 splice user + initial assistant into
  //                                 conversation, sandbox prewarm, abort
  //                                 controller setup) moved to
  //                                 chat-prepare-send.ts. Ceiling lowered
  //                                 to 1,400 — closes the cap-ratchet
  //                                 feedback loop the 4-26 architecture
  //                                 snapshot called out and forces the next
  //                                 feature to either fit or extract.
  //   Phase 6 (acquire+finalize):   1,349 -> 1,275 after sendMessage's run-
  //                                 session bookends (acquireRunSession +
  //                                 finalizeRunSession) moved to
  //                                 chat-run-session.ts. Ceiling lowered
  //                                 to 1,330. The remaining inline weight
  //                                 in sendMessage is the round loop body,
  //                                 which routes through chat-send.ts's
  //                                 already-extracted helpers; further
  //                                 reduction would mean pulling apart the
  //                                 loop's control flow rather than
  //                                 extracting more sibling functions.
  //   Phase 7 (queued-follow-up):   1,329 -> 1,276 after the four pure
  //                                 helpers (getQueuedFollowUpOptions,
  //                                 summarizeQueuedInputPreview,
  //                                 toQueuedFollowUp, toPendingSteerRequest)
  //                                 moved to lib/queued-follow-up-utils.ts.
  //                                 Ceiling lowered to 1,290.
  //   Phase 8 (round-loop body):    1,276 -> 1,045 after the for-loop body
  //                                 inside sendMessage (round counter +
  //                                 streaming + steer drain + tool dispatch
  //                                 + turn outcome) moved to
  //                                 chat-round-loop.ts as runRoundLoop.
  //                                 The duplicated pending-steer drain
  //                                 (formerly two ~80-line blocks for
  //                                 before-tools and after-turn) collapsed
  //                                 into a single helper inside the new
  //                                 module. useChat now holds only the
  //                                 try/catch/finally bookend (LOOP_FAILED
  //                                 emission + finalizeRunSession +
  //                                 nextFollowUp scheduling, which depends
  //                                 on `sendMessage` itself). Ceiling
  //                                 lowered to 1,060.
  //   Phase 9 (three-pack):         1,045 -> 892 across three extractions
  //                                 on 2026-05-01: (a) the dirty/deleted
  //                                 ID sets + retry-with-cap-at-3 flush
  //                                 lifecycle moved to
  //                                 useConversationPersistence; (b) the
  //                                 active-run queue/steer/short-circuit
  //                                 branch in sendMessage moved to
  //                                 chat-active-run-router as a pure
  //                                 routeActiveRunInput function; (c) the
  //                                 auto-create-or-switch effect moved to
  //                                 useChatAutoSwitch with a pure
  //                                 decideAutoSwitchAction state machine
  //                                 inside. ~30 new test cases pin
  //                                 previously-uncovered behavior. Ceiling
  //                                 lowered to 950.
  {
    files: ['src/hooks/useChat.ts'],
    rules: {
      'max-lines': ['error', { max: 950 }],
    },
  },
  // Containment guard for chat-send.ts. The dispatcher is the largest
  // remaining module after the useChat re-extraction. 2026-05-01 split it
  // into four files: chat-send.ts (processAssistantTurn dispatcher),
  // chat-send-types.ts (SendLoopContext + handler interfaces),
  // chat-send-helpers.ts (pulse / delegate / chat-hook / verification /
  // post-tool-policy helpers), and chat-stream-round.ts (the streaming
  // wrapper). chat-send.ts dropped 1,740 -> 1,272. Cap is set above the
  // current count to leave a small headroom but well under the
  // pre-extraction state. Phase 2 (splitting processAssistantTurn along
  // its three internal phases) would ratchet this down further.
  {
    files: ['src/hooks/chat-send.ts'],
    rules: {
      'max-lines': ['error', { max: 1300 }],
    },
  },
]);
