/**
 * Runtime intervention contract.
 *
 * A steer keeps the loop alive with runtime-generated guidance. A block refuses
 * an action or stops the run at a hard boundary. This is deliberately a small
 * data contract, not a hook framework.
 */

export type RuntimeInterventionMode = 'steer' | 'block';

export type RuntimeInterventionPoint =
  | 'after_model'
  | 'before_tool'
  | 'after_tool'
  | 'delivery_gate';

export interface RuntimeIntervention<TContext = unknown> {
  readonly mode: RuntimeInterventionMode;
  readonly point: RuntimeInterventionPoint;
  /** Stable policy/source label, e.g. `tool_budget` or `tool_call_recovery`. */
  readonly source: string;
  /** Stable reason code suitable for logs and run events. */
  readonly reason: string;
  /** Optional short operator-facing summary. */
  readonly message?: string;
  /** Optional model-facing guidance generated by runtime code. */
  readonly guidance?: string;
  /** Optional structured state the policy used to decide. */
  readonly context?: TContext;
}

export type RuntimeInterventionInput<TContext = unknown> = RuntimeIntervention<TContext>;

export function createRuntimeIntervention<TContext>(
  input: RuntimeInterventionInput<TContext>,
): RuntimeIntervention<TContext> {
  return { ...input };
}

export function createSteerIntervention<TContext>(
  input: Omit<RuntimeInterventionInput<TContext>, 'mode'>,
): RuntimeIntervention<TContext> {
  return createRuntimeIntervention({ ...input, mode: 'steer' });
}

export function createBlockIntervention<TContext>(
  input: Omit<RuntimeInterventionInput<TContext>, 'mode'>,
): RuntimeIntervention<TContext> {
  return createRuntimeIntervention({ ...input, mode: 'block' });
}

export function isSteerIntervention(
  intervention: RuntimeIntervention | null | undefined,
): intervention is RuntimeIntervention {
  return intervention?.mode === 'steer';
}

export function isBlockIntervention(
  intervention: RuntimeIntervention | null | undefined,
): intervention is RuntimeIntervention {
  return intervention?.mode === 'block';
}
